#ifndef _GLOBAL_H
#define _GLOBAL_H
#include "Buffer.h"
#include <math.h>
#include <string>
using namespace std;
struct streamData{
	float  x;
};
extern Buffer<streamData> Source_0_LowPassFilterX_1;
extern Buffer<streamData> LowPassFilterX_1_FMDemodulatorX_2;
extern Buffer<streamData> FMDemodulatorX_2_Duplicate_3;
extern Buffer<streamData> Duplicate_3_Duplicate_4;
extern Buffer<streamData> Duplicate_3_Duplicate_10;
extern Buffer<streamData> Duplicate_3_Duplicate_16;
extern Buffer<streamData> Duplicate_3_Duplicate_22;
extern Buffer<streamData> Duplicate_3_Duplicate_28;
extern Buffer<streamData> Duplicate_3_Duplicate_34;
extern Buffer<streamData> Duplicate_3_Duplicate_40;
extern Buffer<streamData> Duplicate_3_Duplicate_46;
extern Buffer<streamData> Duplicate_3_Duplicate_52;
extern Buffer<streamData> Duplicate_3_Duplicate_58;
extern Buffer<streamData> Duplicate_4_LowPassFilterX_5;
extern Buffer<streamData> Duplicate_4_LowPassFilterX_6;
extern Buffer<streamData> LowPassFilterX_5_join_7;
extern Buffer<streamData> LowPassFilterX_6_join_7;
extern Buffer<streamData> join_7_Subtracter_8;
extern Buffer<streamData> Subtracter_8_AmplifyX_9;
extern Buffer<streamData> AmplifyX_9_join_64;
extern Buffer<streamData> Duplicate_10_LowPassFilterX_11;
extern Buffer<streamData> Duplicate_10_LowPassFilterX_12;
extern Buffer<streamData> LowPassFilterX_11_join_13;
extern Buffer<streamData> LowPassFilterX_12_join_13;
extern Buffer<streamData> join_13_Subtracter_14;
extern Buffer<streamData> Subtracter_14_AmplifyX_15;
extern Buffer<streamData> AmplifyX_15_join_64;
extern Buffer<streamData> Duplicate_16_LowPassFilterX_17;
extern Buffer<streamData> Duplicate_16_LowPassFilterX_18;
extern Buffer<streamData> LowPassFilterX_17_join_19;
extern Buffer<streamData> LowPassFilterX_18_join_19;
extern Buffer<streamData> join_19_Subtracter_20;
extern Buffer<streamData> Subtracter_20_AmplifyX_21;
extern Buffer<streamData> AmplifyX_21_join_64;
extern Buffer<streamData> Duplicate_22_LowPassFilterX_23;
extern Buffer<streamData> Duplicate_22_LowPassFilterX_24;
extern Buffer<streamData> LowPassFilterX_23_join_25;
extern Buffer<streamData> LowPassFilterX_24_join_25;
extern Buffer<streamData> join_25_Subtracter_26;
extern Buffer<streamData> Subtracter_26_AmplifyX_27;
extern Buffer<streamData> AmplifyX_27_join_64;
extern Buffer<streamData> Duplicate_28_LowPassFilterX_29;
extern Buffer<streamData> Duplicate_28_LowPassFilterX_30;
extern Buffer<streamData> LowPassFilterX_29_join_31;
extern Buffer<streamData> LowPassFilterX_30_join_31;
extern Buffer<streamData> join_31_Subtracter_32;
extern Buffer<streamData> Subtracter_32_AmplifyX_33;
extern Buffer<streamData> AmplifyX_33_join_64;
extern Buffer<streamData> Duplicate_34_LowPassFilterX_35;
extern Buffer<streamData> Duplicate_34_LowPassFilterX_36;
extern Buffer<streamData> LowPassFilterX_35_join_37;
extern Buffer<streamData> LowPassFilterX_36_join_37;
extern Buffer<streamData> join_37_Subtracter_38;
extern Buffer<streamData> Subtracter_38_AmplifyX_39;
extern Buffer<streamData> AmplifyX_39_join_64;
extern Buffer<streamData> Duplicate_40_LowPassFilterX_41;
extern Buffer<streamData> Duplicate_40_LowPassFilterX_42;
extern Buffer<streamData> LowPassFilterX_41_join_43;
extern Buffer<streamData> LowPassFilterX_42_join_43;
extern Buffer<streamData> join_43_Subtracter_44;
extern Buffer<streamData> Subtracter_44_AmplifyX_45;
extern Buffer<streamData> AmplifyX_45_join_64;
extern Buffer<streamData> Duplicate_46_LowPassFilterX_47;
extern Buffer<streamData> Duplicate_46_LowPassFilterX_48;
extern Buffer<streamData> LowPassFilterX_47_join_49;
extern Buffer<streamData> LowPassFilterX_48_join_49;
extern Buffer<streamData> join_49_Subtracter_50;
extern Buffer<streamData> Subtracter_50_AmplifyX_51;
extern Buffer<streamData> AmplifyX_51_join_64;
extern Buffer<streamData> Duplicate_52_LowPassFilterX_53;
extern Buffer<streamData> Duplicate_52_LowPassFilterX_54;
extern Buffer<streamData> LowPassFilterX_53_join_55;
extern Buffer<streamData> LowPassFilterX_54_join_55;
extern Buffer<streamData> join_55_Subtracter_56;
extern Buffer<streamData> Subtracter_56_AmplifyX_57;
extern Buffer<streamData> AmplifyX_57_join_64;
extern Buffer<streamData> Duplicate_58_LowPassFilterX_59;
extern Buffer<streamData> Duplicate_58_LowPassFilterX_60;
extern Buffer<streamData> LowPassFilterX_59_join_61;
extern Buffer<streamData> LowPassFilterX_60_join_61;
extern Buffer<streamData> join_61_Subtracter_62;
extern Buffer<streamData> Subtracter_62_AmplifyX_63;
extern Buffer<streamData> AmplifyX_63_join_64;
extern Buffer<streamData> join_64_AnnoyX_65;
extern Buffer<streamData> AnnoyX_65_Sink_66;
#endif
